version: "3.9"

services:
  inquiry:
    container_name: Inquiry
    ports:
      - "8877:8877"
    expose:
      - "8877"
    build:
      context: ./
      dockerfile: InquiryDockerfile
    volumes:
      - ./logs:/app/logs
    restart:
      always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webhook_rcv:
    container_name: Webhook_Receiver
    ports:
      - "80:80"
    expose:
      - 80
    build:
      context: ./
      dockerfile: WebhookDockerfile
    volumes:
      - ./logs:/app/logs
    restart:
      always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini


volumes:
  postgres-data:
    driver: local
  prometheus_data:
  grafana_data:
