version: "3.9"

services:
  inquiry:
    container_name: Inquiry
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./logs:/app/logs
    networks:
      - inquiry-network
    restart:
      always
    depends_on:
      - postgres

  postgres:
    container_name: Postgres
    image: postgres:latest
    networks:
      - inquiry-network
    restart:
      always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

networks:
  inquiry-network:
    external: false


volumes:
  postgres-data:
    driver: local